### PR TITLE
GH-484: Add MajorUpgrade element to msi build definition

### PR DESCRIPTION
**Pull request by ShadowXVII**
One commit is only whitespace, so please see changes in commit https://github.com/cloudflare/cloudflared/commit/28294be470aeb39aa7c58d776494d7aed9b6ff3c

I also tried to build things but the build instructions link is dead on readme.md. So untested 😅 

#484

### CODE REVIEW

**Review by joliveirinha — APPROVED** [review]

**Comment by sudarshan-reddy** [comment]
@ShadowXVII you can probably test it by running

`make cloudflared-msi` and then running the msi to see if it has the intended effect.

**Comment by ShadowXVII** [comment]
> make cloudflared-msi

Yes, was trying to do that, but running into errors around the msi tooling

```
make cloudflared-msi
wixl --define Version=2022.12.1-2-gde4fd472 --define Path=./cloudflared --output cloudflared-2022.12.1-2-gde4fd472-amd64.msi cloudflared.wxs

(wixl:1289): wixl-ERROR **: 10:17:03.559: wix.vala:218: unhandled child Component node Environment
```

I have msitools and wixl v 0.100-1

**Comment by sudarshan-reddy** [comment]
Ah yes indeed: https://github.com/sudarshan-reddy/msitools/releases has a patch for environment.

I’ll make sure to update the readme with this.

**Comment by ShadowXVII** [comment]
What's the best way to get those tools into PATH? I had built them, but should I remove packages wixl and msitools as well? Or do they supersede some of the tools? Not sure what is part of what, sorry!

**Comment by sudarshan-reddy** [comment]
It can be confusing indeed.  I’d recommend putting them somewhere temporary and pointing the wixl  call [here](https://github.com/cloudflare/cloudflared/blob/master/Makefile#L190)  to that directory.

**Comment by ShadowXVII** [comment]
Okay, I think the * for Product ID is the trick. It sets it automatically during compile and allows for upgrade.
I think it's a terrible name, but I imagine that's not the most terrible thing about MSIs ;)

I was having trouble getting a Windows build so I used a dummy cloudflared file, but the MSI installed/upgraded.
Happy to do some more test with some binary MSIs if needed.

**Comment by sudarshan-reddy** [comment]
LGTM @ShadowXVII . Would you mind squashing the commits please? Thanks for this PR!

**Review by sudarshan-reddy — APPROVED** [review]

**Comment by ShadowXVII** [comment]
@sudarshan-reddy done

**Comment by ShadowXVII** [comment]
Cool thanks @sudarshan-reddy . Let me know if you need anything else @DevinCarr

**Pull request merged**
