### PR TITLE
Adding support for multi-architecture images and binaries

### PR DESCRIPTION
**Pull request by xUnholy**
Fixes: 
- #140 
- #115 
- #60 

Note: Should also consider consolidating the following pull request if you wish to support releasing the binary.
- #173

### CODE REVIEW

**Comment by unicomp21** [comment]
Will this work on the newly released m6g/graviton2 processors from AWS as well?

**Comment by xUnholy** [comment]
Bump**
@sssilver would you know who is the best person to review this pull request?

**Comment by sssilver** [comment]
@xUnholy Hi! Sorry this took a while. We'll get this reviewed in a day or so and get it merged! Thank you so much for your contribution~

**Comment by xUnholy** [comment]
Thanks @sssilver & @acmacalister - I just wasn't sure what the process was to have this reviewed. Appreciate your time :+1:

**Comment by acmacalister** [comment]
@xUnholy looks good, thanks for your PR! As @Michael9127 noted, can we add Windows as build arch?

**Comment by xUnholy** [comment]
I've squashed commits as requested, usually, I find it easier to just squash and merge but I'm easy either way.

In terms of testing and trying to do the windows, I'd rather than was work for a separate PR at this stage, correct me if I'm wrong but the existing logic didn't support windows either, for now, I'd like to just get these changes while I debug on a new branch the windows specific issue.

@Michael9127 @acmacalister thoughts?

**Comment by xUnholy** [comment]
Just used the logic `TARGET_OS=windows make cloudflared` which works when building until it hits a failure for the following reason:

```
cmd/cloudflared/windows_service.go:19:2: errors redeclared as imported package name
	previous declaration at cmd/cloudflared/windows_service.go:16:2
make: *** [cloudflared] Error 2
```

**Comment by acmacalister** [comment]
Thanks @xUnholy. Surprised it has a build error, as we distribute Windows builds on every release

**Comment by xUnholy** [comment]
No worries, using the command I mentioned and with the small fix I can build windows fine with these changes.

Please let me know if there is anything else you'd like from my end.

**Pull request merged**
