### PR TITLE
Fix missing space in LICENSE file

### PR DESCRIPTION
**Pull request by whalehub**

### CODE REVIEW

**Comment by whalehub** [comment]
@sudarshan-reddy requesting review

**Review by sssilver — APPROVED** [review]

**Comment by whalehub** [comment]
@sssilver Is this ready to be merged as-is?

**Review by Maxnoue — CHANGES_REQUESTED** [review]
Want change

**Comment by whalehub** [comment]
@sssilver Is this ready to be merged as-is?

**Comment by sudarshan-reddy** [comment]
Closed as this is no longer the active license.

**Pull request closed without merging**
