### PR TITLE
Regnaio/location

### PR DESCRIPTION
**Pull request by chippytech**
as

### CODE REVIEW

**Comment by sudarshan-reddy** [comment]
Hello @chippytech ! what is the intention behind this PR?

**Comment by chippytech** [comment]
To add location to cloudflared.

**Comment by sudarshan-reddy** [comment]
I would like to suggest you be more descriptive.

What does this change do?

What warranted it?

Have you tested it? Do you have  demonstrations?

Why do you think this will benefit others?

Once we have details like this, we can debate if we want to add this to `cloudflared`

**Comment by chippytech** [comment]
To add location to cloudflared

**Comment by sudarshan-reddy** [comment]
I'm sorry @chippytech . Without the information asked for it is impossible to understand and deliberate about the merits of this PR. I suggest reopening this when you have this information. 🙂

**Comment by chippytech** [comment]
To add location to cloudflared config.

**Comment by fabiopires** [comment]
This PR is not very useful, but the functionality that it's trying to merge is.

The original author has described [here](https://github.com/cloudflare/cloudflared/issues/563#issuecomment-1081779878) what is the goal behind this merge. In fact, it will address the possibility of manipulating the location to which a request should go.

Hopefully this can be re-opened and potentially merged.

**Pull request closed without merging**
