### PR TITLE
connect via proxy

### LINKED ISSUE #350: Cloudflared tunnel via proxy
I see that `cloudflared access` has support for a proxy #317.

I'm trying to use `cloudflared tunnel` as well behind a corporate firewall, but this doesn't seem to support proxy? The connection attempt is always direct.

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #350
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by sudarshan-reddy** [comment]
Thanks for this @davidkarlsen. I have a few requests. 

 The PR stills seems to be in draft. Is that the intent? 
 
 Can you also add a unit test to demonstrate the intent for this change please?

**Comment by davidkarlsen** [comment]
Yeah, it's still a draft, it didn't work out as expected (I tried building the patched version and running it locally). Some guidance on the codebase could be useful - am I in the right place at all?

**Comment by sudarshan-reddy** [comment]
That's why I was looking for a unit test.

But let's start there. Can you tell me what you want to accomplish?

**Comment by davidkarlsen** [comment]
See https://github.com/cloudflare/cloudflared/issues/350#issuecomment-901830376, even when defining http_proxy/https_proxy these are not picked up, and hence connection is attempted directly. This won't work as we're firewalled from the internet, and need to pass through forward proxy.

**Comment by sudarshan-reddy** [comment]
Circling back to this, This PR is still a draft. 

Happy to revisit this. Do you want to put up an explanation as to what you want to achieve (I see the issue you linked but I think an express statement helps) and we can take if up from there?

**Comment by BeautyYuYanli** [comment]
> Circling back to this, This PR is still a draft.
> 
> Happy to revisit this. Do you want to put up an explanation as to what you want to achieve (I see the issue you linked but I think an express statement helps) and we can take if up from there?

I think it is something like :
```
HTTP_PROXY=http://127.0.0.1:8080/ cloudflared tunnel run ...
```

similar to #317

**Comment by davidkarlsen** [comment]
> Circling back to this, This PR is still a draft.
> 
> Happy to revisit this. Do you want to put up an explanation as to what you want to achieve (I see the issue you linked but I think an express statement helps) and we can take if up from there?

It's really outlined in #350 - so basically be able to run the tunnelling through a http-proxy.
We moved to alternative solutions, so I don't have more time to work on this.

**Comment by yggdrasil-tynor** [comment]
> > Circling back to this, This PR is still a draft.
> > Happy to revisit this. Do you want to put up an explanation as to what you want to achieve (I see the issue you linked but I think an express statement helps) and we can take if up from there?
> 
> It's really outlined in #350 - so basically be able to run the tunnelling through a http-proxy. We moved to alternative solutions, so I don't have more time to work on this.

@davidkarlsen  Would you like to share how you solved this? We are also looking at how we can proxy the traffic.

**Comment by davidkarlsen** [comment]
> > It's really outlined in #350 - so basically be able to run the tunnelling through a http-proxy. We moved to alternative solutions, so I don't have more time to work on this.
> 
> @davidkarlsen Would you like to share how you solved this? We are also looking at how we can proxy the traffic.

We moved to an alternative vendor as it could not support our usecase due to this limitation.

**Comment by yggdrasil-tynor** [comment]
> > > It's really outlined in #350 - so basically be able to run the tunnelling through a http-proxy. We moved to alternative solutions, so I don't have more time to work on this.
> > 
> > 
> > @davidkarlsen Would you like to share how you solved this? We are also looking at how we can proxy the traffic.
> 
> We moved to an alternative vendor as it could not support our usecase due to this limitation.

You mean another vendor than CF? (tunnels)?

**Pull request closed without merging**
