### PR TITLE
Add s390x architecture support

### PR DESCRIPTION
**Pull request by misakano7545**

### CODE REVIEW

**Review by nmldiegues — APPROVED** [review]

**Comment by nmldiegues** [comment]
@sssilver  this is good to merge;  cloudflared compiles on s390x fine

**Comment by misakano7545** [comment]
> @sssilver this is good to merge; cloudflared compiles on s390x fine

image

Yes I tried for build, it fine

**Review by nmldiegues — APPROVED** [review]

**Comment by Lemonawa** [comment]
you can get a free s390x virtual machine at https://linuxone.cloud.marist.edu

**Review by sssilver — APPROVED** [review]

**Comment by Lemonawa** [comment]
> > @sssilver this is good to merge; cloudflared compiles on s390x fine
> 
> Why not release s390x version?

They use the robot to complete the build, so the robot's code may still not update

**Comment by Lemonawa** [comment]
@nmldiegues @sssilver @bretthoerner

**Comment by xcx0902** [comment]
> > @sssilver this is good to merge; cloudflared compiles on s390x fine
> 
> image
> 
> Yes I tried for build, it fine

How you compiled it? I cannot compile at all. What are your compile commands?

**Pull request merged**
