### PR TITLE
Handle exit code on err

### LINKED ISSUE #96: cloudflared returning zero exit code on error
If cloudflared starts up before networking and DNS resolution is up and running, it will throw an error and exit. However, this error is returning a zero/success exit code.. as such launchd on Darwin sees that the application intended to exit, and doesn't restart it.

```
$ cloudflared
INFO[0000] Build info: {GoOS:darwin GoVersion:go1.11.1 GoArch:amd64} 
INFO[0000] Version 2019.4.1                             
INFO[0000] Flags                                         hostname=example.com proxy-dns-upstream="https://1.1.1.1/dns-query, https://1.0.0.1/dns-query" url="ssh://127.0.0.1:22"
INFO[0000] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/ 
INFO[0000] Starting metrics server                       addr="127.0.0.1:49693"
INFO[0000] Proxying tunnel requests to http://127.0.0.1:49694 
ERRO[0000] Error looking up Cloudflare edge IPs: the DNS query failed: lookup _warp._tcp.cloudflarewarp.com on [::1]:53: read udp [::1]:52309->[::1]:53: read: connection refused 
ERRO[0000] Please try the following things to diagnose this issue: 
ERRO[0000]   1. ensure that cloudflarewarp.com is returning "warp" service records. 
ERRO[0000]      Run your system's equivalent of: dig srv _warp._tcp.cloudflarewarp.com 
ERRO[0000]   2. ensure that your DNS resolver is not returning compressed SRV records. 
ERRO[0000]      See GitHub issue https://github.com/golang/go/issues/27546 
ERRO[0000]      For example, you could use Cloudflare's 1.1.1.1 as your resolver: 
ERRO[0000]      https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/ 
INFO[0000] ResolveEdgeIPs err                           
ERRO[0000] Quitting due to error                         error="Could not lookup srv records on _warp._tcp.cloudflarewarp.com: lookup _warp._tcp.cloudflarewarp.com on [::1]:53: read udp [::1]:52309->[::1]:53: read: connection refused"
INFO[0000] Metrics server stopped                       
$ echo $?
0
$ 
```

If instead this reported a non-zero exit code, launchd would see that the process failed and it should attempt to restart it.

### PR DESCRIPTION
**Pull request by cblecker**
fixes #96.

I've tested this locally, and it seems to fix the issue described on #96.

cc: @nickvollmar

### CODE REVIEW

**Comment by cblecker** [comment]
I also installed a build with this on my server, and it works just as intended. cloudflared now starts up at boot, even if network/DNS isn't immediately available.

**Comment by cblecker** [comment]
ping. looking for review on this :)

**Comment by sssilver** [comment]
Hi @cblecker !

Thanks for the PR, sorry it took a bit to take a look at it.

The code changes look good, do you mind amending your commit message to include the issue number it resolves?

Thanks!

**Comment by cblecker** [comment]
@sssilver Added a more detailed commit message, including a reference to the issue.

**Pull request merged**
