### PR TITLE
Fix flaky tests

### PR DESCRIPTION
**Pull request by moofMonkey**
This PR should potentially eliminate (or at least greatly reduce) `testActiveSessionNotClosed` flakiness at the Github CI.
As described in https://github.com/cloudflare/cloudflared/pull/766#issuecomment-1264874623, this is caused by an eager timeout due to insufficient CI CPU resources.

I didn't maintain the same ratio of `activeTime = closeAfterIdle * 5` as it'd make tests run ~50% longer while having potentially no difference in behavior besides running for a longer period of time.

Side effect: fixed datagramsession tests are now ~1.5s longer - 1.026s previously vs ~2.513s with this PR.

This PR also fixes race condition in `TestConnections` caused by concurrent read/write operations to shared variable `replayer` by newly created goroutines, which I got on CI after trying to fix the `testActiveSessionNotClosed`, CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3173213348/jobs/5168571799#step:4:1523), Copy for the future reference is [here](https://gist.github.com/moofMonkey/ba619b823ec52bbd749071873e8451b3), as CI logs have limited lifetime.

### CODE REVIEW

**Comment by moofMonkey** [comment]
There are 2 flaky tests left that I see, but I don't understand their problems due to the lack of cloudflared internals knowledge.
1) `TestManagerCtxDoneCloseSessions`: [here](https://github.com/moofMonkey/cloudflared/actions/runs/3173534540/jobs/5169259266#step:4:949), [here](https://github.com/moofMonkey/cloudflared/actions/runs/3173702114/jobs/5169607820#step:4:924) and [here](https://github.com/moofMonkey/cloudflared/actions/runs/3173703611/jobs/5169611204#step:4:924) - 3 out of 10 tests
2) `TestDatagram`: [here](https://github.com/moofMonkey/cloudflared/actions/runs/3173550348/jobs/5169292561#step:4:1531) - 1 out of 10 tests, looks like CI environment specific

Tests fixed by this PR doesn't seem to be flaky anymore given [10 runs](https://github.com/moofMonkey/cloudflared/actions/workflows/check.yaml) out of which they didn't fail once.

**Comment by moofMonkey** [comment]
`TestManagerCtxDoneCloseSessions` has a race condition due to select not having guaranteed execution order in Golang.
Citing the spec, https://go.dev/ref/spec#Select_statements
> If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection.

https://github.com/cloudflare/cloudflared/blob/bad2e8e812d898c32b0aacc66a6f947109eaf24a/datagramsession/manager_test.go#L196-L197
https://github.com/cloudflare/cloudflared/blob/bad2e8e812d898c32b0aacc66a6f947109eaf24a/datagramsession/session.go#L64-L68
https://github.com/cloudflare/cloudflared/blob/bad2e8e812d898c32b0aacc66a6f947109eaf24a/datagramsession/session.go#L86-L89
https://github.com/cloudflare/cloudflared/blob/bad2e8e812d898c32b0aacc66a6f947109eaf24a/datagramsession/manager.go#L69-L70
https://github.com/cloudflare/cloudflared/blob/bad2e8e812d898c32b0aacc66a6f947109eaf24a/datagramsession/manager.go#L88-L95

There are two possible ways to fix this - either remove `require.False(t, closedByRemote)` check, or check for `context.Canceled` in `manager.shutdownSessions()`. I did it the second way, but that could be changed if needed.
I made [a lot more CI runs](https://github.com/moofMonkey/cloudflared/actions/workflows/check.yaml) and it's not flaky anymore.

Other tests that were addressed and didn't fail in at least last 15 CI runs:
1) `TestLongSiteWithDictionaries` was flaky, CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3178437927/jobs/5179924713#step:4:1165). That was caused by insufficient CPU resources.
  I attempted to fix it by using `errGroup.SetLimit()`.
2) `TestConnections` was still flaky. CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3179044115/jobs/5181137089#step:4:1497).
  I attempted to fix this by adding a waitgroup for pipedRequestBody case, and the previous fix isn't needed anymore as goroutine should be done at the time of the test ending, and tests aren't being run in parallel.
3) `TestDatagram` flakiness still depends on the CI environment, fresh CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3179455150/jobs/5181969919#step:4:1531), this only occurs on the MacOS CI.
  I attempted to fix it by failing the test instead of timing it out on error and by waiting for the MTU discovery for a bit longer (300ms instead of 100ms).
4) `TestQUICServer` was timing out flaky, CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3178436872/jobs/5179922865#step:4:857).
  I attempted to fix it by failing the test instead of timing it out on error in case server doesn't finish, by waiting for the server to start.
 
Other tests that weren't addressed after the last fail:
1) `TestGracefulShutdownHTTP2` is flaky, CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3179975928/jobs/5183030263#step:4:825) and [here](https://github.com/moofMonkey/cloudflared/actions/runs/3179180106/jobs/5181410590#step:4:825).
2) `testActiveSessionNotClosed` is still a bit flaky, CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3179267297/jobs/5181579156#step:4:932) and [here](https://github.com/moofMonkey/cloudflared/actions/runs/3179701174/jobs/5182462826).

`mockOriginProxyWithRequest.ProxyHTTP()` also sleeps for just 5ns in `/slow_echo_body` due to `time.Sleep(5)`, and duration (such as `time.Millisecond`) is probably meant to be specified there.

**Comment by moofMonkey** [comment]
`TestGracefulShutdownHTTP2` didn't fail in last 20 CI runs, other tests didn't fail in last 36 CI runs.
That's 0 failed CI runs out of 20 compared to 25 failed CI runs out of 30 most recent ones on master.

I think that's good enough, this PR is ready for review now.

**Comment by moofMonkey** [comment]
`TestQUICServer` is still a bit flaky. CI logs are [here](https://github.com/moofMonkey/cloudflared/actions/runs/3186173579/jobs/5196509075#step:4:885).

**Review by 01SMD — APPROVED** [review]

**Comment by chungthuang** [comment]
@moofMonkey thank you for looking into this. We have improved the tests over the last 2 years. Feel free to rebase and open again if they are still flaky.

**Pull request closed without merging**
