### PR TITLE
➕ Dockerfile.arm to support arm 32bit

### PR DESCRIPTION
**Pull request by jeankhawand**
- [x] had to build it on my AllWinner H2 SoC which is running arm 32bit 
- [x] it is working with no issues
- [x] it took some time to build dependencies – would be nice to have it accessible from docker registry cause it will require some effort when new version of cloudflared is out to rebuild....

### CODE REVIEW

**Comment by jeankhawand** [comment]
```
2023-06-10T15:47:41Z INF Starting tunnel tunnelID=REDACTED 
2023-06-10T15:47:41Z INF Version 31d3670d
2023-06-10T15:47:41Z INF GOOS: linux, GOVersion: go1.19.10, GoArch: arm
2023-06-10T15:47:41Z INF Settings: map[no-autoupdate:true token:*****]
2023-06-10T15:47:41Z INF Generated Connector ID: REDACTED 
2023-06-10T15:47:41Z INF Initial protocol quic
2023-06-10T15:47:42Z INF ICMP proxy will use 172.18.0.2 as source for IPv4
2023-06-10T15:47:42Z INF ICMP proxy will use :: as source for IPv6
2023-06-10T15:47:42Z INF Starting metrics server on 127.0.0.1:35601/metrics
2023-06-10T15:47:42Z INF Registered tunnel connection connIndex=0 connection=REDACTED event=0 ip=198.41.192.7 location=CDG protocol=quic
```

**Comment by sudarshan-reddy** [comment]
Thanks for this work @jeankhawand . I'm going to have to test this against our internal CI (since that's what builds the docker images) and get back to you.

**Comment by jeankhawand** [comment]
closes #987

**Comment by ahlixinjie** [comment]
waiting for this to be merged, so my mikrotik device can use it😢

**Comment by TylerMitton** [comment]
@sudarshan-reddy , do you expect this will be merged? thankful to you and @jeankhawand for your work on this.

**Comment by maijs** [comment]
You can build an arm image on a Mac Silicon and transfer the image to Mikrotik with the following stpeps:
1. Run `docker buildx ls` and check if your computer can build `linux/arm/v7` platform images.
2. Checkout the branch of the PR: `git clone -b feature/support-armhf https://github.com/jeankhawand/cloudflared.git`
3. Change the directory: `cd cloudflared`
4. Build an image: `docker buildx build --platform linux/arm/v7 . -t MYNAME/cloudflared` (change MYNAME to your username)
5. Make sure the that image has been built: `docker image ls`
5. Save the image on the disk: `docker image save -o docker_cloudflared_arm IMAGE_ID`
6. Copy the image file to the Mikrotik device.

**Comment by maijs** [comment]
I tested the PR and can confirm that it works. Looking forward to see it merged.

**Comment by maijs** [comment]
@jeankhawand Could you please make two changes to the PR?

1. Rebase the feature branch against the current `cloudflare:master` branch.
2. Update the golang version in the `Dockerfile.arm` file to `FROM golang:1.20.6 as builder` to match the current Dockerfile.* in upstream repo?

**Comment by farnos85** [comment]
> You can build an arm image on a Mac Silicon and transfer the image to an arm-based Mikrotik router with the following stpeps:
> 
> 1. Run `docker buildx ls` and check if your computer can build `linux/arm/v7` platform images.
> 2. Checkout the branch of the PR: `git clone -b feature/support-armhf https://github.com/jeankhawand/cloudflared.git`
> 3. Change the directory: `cd cloudflared`
> 4. Build an image: `docker buildx build --platform linux/arm/v7 . -t MYNAME/cloudflared` (change MYNAME to your username)
> 5. Make sure the that image has been built: `docker image ls`
> 6. Save the image on the disk: `docker image save -o docker_cloudflared_arm IMAGE_ID`
> 7. Copy the image file to the Mikrotik device.

I tried this procedure on my mikrotik router with arm architecture, but I had this error "execve: Exec format error"

**Comment by maijs** [comment]
@farnos85 On which Mikrotik router are you trying to create a container?

**Comment by farnos85** [comment]
> @farnos85 On which Mikrotik router are you trying to create a container?

https://mikrotik.com/product/hap_ac3

**Comment by cldparisi** [comment]
follow it

**Comment by maijs** [comment]
> > @farnos85 On which Mikrotik router are you trying to create a container?
> 
> https://mikrotik.com/product/hap_ac3

@farnos85 The result of the steps I described was tested on a [HAP AC2](https://mikrotik.com/product/hap_ac2), which also has an arm 32bit processor. Need more testing from other people I suppose.

**Comment by farnos85** [comment]
> > > @farnos85 On which Mikrotik router are you trying to create a container?
> > 
> > 
> > https://mikrotik.com/product/hap_ac3
> 
> @farnos85 The result of the steps I described was tested on a [HAP AC2](https://mikrotik.com/product/hap_ac2), which also has an arm 32bit processor. Need more testing from other people I suppose.

UPDATE:
image built on Raspberry PI 4 with Linux raspberrypi 6.1.21-v8+ --> execve: Exec format error
image built on GCP VM with Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1042-gcp x86_64) --> works correctly

**Comment by joliveirinha** [comment]
We are not looking to support this platform at this time. 
We may re-evaluate this in the future, and in that case, this would need to be done with proper context of our internal pipelines.

We appreciate your contribution and interest. thanks

**Pull request closed without merging**
